---
 - name: carete webshkiller dir
   file: path=/home/{{ login_user }}/go/src/github.com/KosukeShimofuji/ state=directory mode=0700 owner={{ login_user }} group={{ login_user }} recurse=yes

 - name: git clone webshkiller
   git: repo=https://github.com/KosukeShimofuji/WebSHKiller.git dest=/home/{{ login_user }}/go/src/github.com/KosukeShimofuji/

