---
 - name: git clone webshkiller
   git: repo=https://github.com/yyuu/pyenv.git dest=/home/{{ login_user }}/.pyenv

 - name: chown pyenv
   file: path=/home/{{ login_user }}/.pyenv owner={{ login_user }} group={{ login_user }} mode=0700

 - name: setting pyenv path to .bashrc
   lineinfile:
    dest='/home/{{ login_user }}/.bashrc'
    state=present
    line='export PATH="$HOME/.pyenv/bin:$PATH"'

 - name: setting pyenv init to .bashrc
   lineinfile:
    dest='/home/{{ login_user }}/.bashrc'
    state=present
    line='eval "$(pyenv init -)"'

 - name: install virtualenv
   git: repo=https://github.com/yyuu/pyenv-virtualenv.git dest=/home/{{ login_user }}/.pyenv/plugins/pyenv-virtualenv
 
 - name: chown virtualenv
   file: path=/home/{{ login_user }}/.pyenv/plugins/pyenv-virtualenv owner={{ login_user }} group={{ login_user }} mode=0700

 - name: setting virtualen path to .bashrc
   lineinfile:
    dest='/home/{{ login_user }}/.bashrc'
    state=present
    line='eval "$(pyenv virtualenv-init -)"'

 - name: install python 2.7.11
   command: su - {{ login_user }} -c "pyenv install 2.7.11"
      creates='/home/{{ login_user }}/.pyenv/versions/2.7.11'

 - name: using python 2.7.11
   command: su - {{ login_user }} -c "pyenv global 2.7.11"

 - name: upgrade pip 
   command: su - {{ login_user }} -c "pip install --upgrade pip"

 - name: install ansible
   command: su - {{ login_user }} -c "pip install ansible"

